# Generated by Django 3.1.3 on 2020-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='Videos'),
        ),
    ]
