# Generated by Django 3.1.3 on 2020-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_auto_20201208_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(blank=True, choices=[('Film and animation', 'Film and animation'), ('Cars and vehicles', 'Cars and vehicles'), ('Music', 'Music'), ('Pets and animals', 'Pets and animals'), ('Sport', 'Sport'), ('Travel and events', 'Travel and events'), ('Gaming', 'Gaming'), ('People and blogs', 'People and blogs'), ('Comedy', 'Comedy'), ('Entertainment', 'Entertainment'), ('News and politics', 'News and politics'), ('How-to and style', 'How-to and style'), ('Education', 'Education'), ('Science and technology', 'Science and technology'), ('Non-profits and activism', 'Non-profits and activism')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
