# Generated by Django 3.1.3 on 2021-01-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_auto_20201228_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk1', models.CharField(blank=True, max_length=1000, null=True)),
                ('chunk2', models.CharField(blank=True, max_length=1000, null=True)),
                ('chunk3', models.CharField(blank=True, max_length=1000, null=True)),
                ('chunk4', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload', to='Videos.upload')),
            ],
        ),
    ]
