# Generated by Django 3.1.3 on 2021-01-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0004_chunkupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkupload',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='Videos/thumbnail'),
        ),
    ]
