# Generated by Django 3.1.3 on 2021-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0005_chunkupload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkupload',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
