# Generated by Django 3.1.3 on 2021-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0006_auto_20210105_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkupload',
            name='video_length',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
