# Generated by Django 3.1.3 on 2021-01-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0007_chunkupload_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkupload',
            name='video_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Videos.upload'),
        ),
        migrations.AlterField(
            model_name='chunkupload',
            name='video_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
