# Generated by Django 3.0.7 on 2021-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0009_auto_20210113_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkupload',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
