# Generated by Django 3.0.7 on 2021-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0010_chunkupload_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
    ]
