# Generated by Django 3.0.7 on 2021-02-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0011_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunkvideo', to='Videos.ChunkUpload'),
        ),
    ]
