# Generated by Django 3.0.7 on 2021-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_picture/libdhkNIevCaHRrjS7oUnTSVSXSv7L5t'),
        ),
    ]
