# Generated by Django 3.0.7 on 2021-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210111_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_picture/JsDMCZnC77BRRJ8ftV0bZ3ZMufloGGUA'),
        ),
    ]
