# Generated by Django 3.0.7 on 2021-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210117_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_picture/6ZtjGf1Yq74FZq9c4JDnudZygXimJHZh'),
        ),
    ]
