# Generated by Django 3.0.7 on 2021-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210124_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_picture/6aJxPPmbVjpPdBzgpA3VoIJaoxEfQOwi'),
        ),
    ]
