# Generated by Django 3.0.7 on 2021-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210208_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_picture/OiSdZS9PNHkCEvFN9ZNGo2Fj9ysaYJz4'),
        ),
    ]
