# Generated by Django 3.0.7 on 2021-01-13 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videos', '0009_auto_20210113_0739'),
        ('Like', '0004_auto_20210113_0739'),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChunkUpdetails', to='Videos.ChunkUpload')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentdetails', to='Comment.Comment')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likedetails', to='Like.Like')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdetails', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videodetails', to='Videos.Upload')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
