# Generated by Django 3.1.3 on 2020-11-25 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfollowing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myfollowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfollow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myfollow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
