# Generated by Django 3.1.3 on 2020-12-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videos', '0002_auto_20201208_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commentuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
                ('commentvideo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentvideo', to='Videos.upload')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
