# Generated by Django 3.1.3 on 2020-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='expression',
            field=models.CharField(choices=[('love', 'love'), ('happy', 'happy'), ('sad', 'sad'), ('angry', 'angry')], max_length=200, null=True),
        ),
    ]
