# Generated by Django 3.1.3 on 2020-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0002_like_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
