# Generated by Django 3.0.7 on 2021-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0003_auto_20201228_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='expression',
            field=models.CharField(choices=[('1', 'love'), ('2', 'happy'), ('3', 'sad'), ('4', 'angry')], max_length=200, null=True),
        ),
    ]
